# Generated by Django 3.1.7 on 2021-03-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Управление')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отдел')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ManyToManyField(blank=True, null=True, related_name='sub_department', to='subordinate_organizations.Department')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('city_phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Городской номер')),
                ('inner_phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Внутренний номер')),
                ('fax', models.CharField(blank=True, max_length=150, null=True, verbose_name='Факс')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес электронной почты')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='subordinate_organizations.department')),
                ('subdepartment', models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_department', to='subordinate_organizations.subdepartment')),
            ],
        ),
    ]
