# Generated by Django 3.1.7 on 2021-04-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subordinate_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subdepartment',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_department', to='subordinate_organizations.subdepartment', verbose_name='Отдел'),
        ),
    ]
