# Generated by Django 3.1.7 on 2021-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinate_organizations', '0003_auto_20210409_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_room',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер кабинета'),
        ),
    ]
