# Generated by Django 3.1.7 on 2021-04-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territorial_bodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subdepartment',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sub_department', to='territorial_bodies.subdepartment', verbose_name='Отдел'),
        ),
    ]
