# Generated by Django 3.1.7 on 2021-03-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_customer_inner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_department', to='phonebook.department'),
        ),
    ]
