# Generated by Django 3.1.7 on 2021-03-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_subdepartment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subdepartment',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_department', to='phonebook.subdepartment'),
        ),
    ]
