# Generated by Django 3.1.7 on 2021-03-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20210322_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=models.ForeignKey(blank=True, max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='phonebook.department'),
        ),
    ]
