# Generated by Django 3.1.7 on 2021-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_auto_20210322_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_room',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер кабинета'),
        ),
    ]
