# Generated by Django 3.1.7 on 2021-03-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_auto_20210322_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdepartment',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='department',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='subdepartment',
            name='date_created',
        ),
    ]
