# Generated by Django 3.1.7 on 2021-03-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0011_auto_20210322_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdepartment',
            name='department',
        ),
    ]
