# Generated by Django 3.1.7 on 2021-04-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0015_auto_20210322_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='phonebook.department'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subdepartment',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_department', to='phonebook.subdepartment'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Отдел'),
        ),
    ]
